Update faqs.md
taikoxyz/docs pull request #75
Opened 2024-03-04 06:20 UTC by faust21k

A new question and answer have been added to the FAQs section:

How do I get a ETH on the Taiko Katla network?

You can use the official Taiko bridge to send your ETH from the Holesky network to the Taiko Katla network.

2024-03-04 06:54 UTC, omahs commented on src/content/docs/resources/faqs.md
> +## How do I get a ETH on the Taiko Katla network?
It should be **How do I get ETH on the Taiko Katla network?** without the 'a'

2024-03-04 07:07 UTC, omahs requested changes

2024-03-04 07:07 UTC, omahs commented on src/content/docs/resources/faqs.md
> +## How do I get a ETH on the Taiko Katla network?
```suggestion
## How do I get ETH on the Taiko Katla network?
```

2024-03-04 10:49 UTC, faust21k commented on src/content/docs/resources/faqs.md
> +## How do I get a ETH on the Taiko Katla network?
my bad sir! just fixed it

2024-03-08 00:24 UTC, d1onys1us approved these changes

2024-03-08 00:24 UTC, merged